### ISSUE TITLE
Add better /setwarp

### ISSUE THREAD

**Issue by PortableGames** [DrexHD/FabricEssentials#4]
Improved /setwarp as it was in KE. To shorten the command from **/warp example** to /example .. I think the command was /setwarp example true

**Comment by DrexHD** [comment]
Registering dynamic root commands is not an intentional feature of bridgadier. I don't plan to implement this. If you wish to replicate this behaviour manually for warps, you should use a mod like [commandaliases](https://modrinth.com/mod/commandaliases).
