### ISSUE TITLE
[BUG (maybe)] Fabric completely ignores this mod as if it never existed.

### ISSUE THREAD

**Issue by Sul4urx** [DrexHD/FabricEssentials#9]
I am using Fabric Essentials 1.2.2+1.21.4 and Fabric Loader 0.16.9. 

For some reason this mod is completely ignored. No errors or anything like that. I even checked the logs, and no signs of this mod. It's not listed in the mods list and none of the commands are available.
I assume the problem lies in the mod itself. I wanted to see if anyone has the exact same behavior.

**Comment by DrexHD** [comment]
Is it possible you are trying to use this mod on your client? It is currently setup to only work on dedicated servers!

**Comment by Sul4urx** [comment]
> Is it possible you are trying to use this mod on your client? It is currently setup to only work on dedicated servers!

Well, it is being used on a Minecraft single player world, so it should be running on dedicated server.
It could be a mod compatibility issue, but I don't think so, because all of them are running on client. 
I did notice something after extracting the mod jar into a folder, in `fabric.mod.json`, `jars[0].file`, It says `META-INF/jars/placeholder-api-2.5.1+1.21.3.jar`, although it should probably be `...+1.21.4.jar`.

**Comment by DrexHD** [comment]
Single player worlds are not considered dedicated servers, but integrated servers. It should be easy to fix this, you can even just try setting the `environment` in `fabric.mod.json` to `*` yourself.

**Comment by Sul4urx** [comment]
> Single player worlds are not considered dedicated servers, but integrated servers. It should be easy to fix this, you can even just try setting the `environment` in `fabric.mod.json` to `*` yourself.

Well I did that and well, Fabric finally knows that it's a mod, but still none of its commands work and they are not listed in auto-fill nor in /help and /fcc. no errors still. It's really weird, because almost all server-side mods support single-player, but this one just doesn't.
